language: generic
sudo: required
services:
  - docker
before_install:
  - docker-compose build -t juchilian/django-api-practice -f docker-compose.yml

script:
  - docker run -e CI=true juchilian/django-api-practice --name test_container
  - docker exec test_container python3 manage.py test
# deploy:
#   provider: elasticbeanstalk
#   region: "ap-northeast-1"
#   app: "django-api-practice"
#   env: "Dockerreact-env"
#   bucket_name: "elasticbeanstalk-ap-northeast-1-676807061826"
#   bucket_path: "django-api-practice"
#   on:
#     branch: main
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
